# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Compute Betweenness Centrality of Network
#' @description This function calculates the betweenness centrality of each node in a network 
#'              based on the adjacency matrix. It uses the Floyd-Warshall algorithm 
#'              implemented in C++ to calculate shortest paths between nodes.
#' @param A A numeric matrix representing the adjacency matrix.
#' @return A numeric vector containing the betweenness centrality scores for each node.
#' @examples
#' \dontrun{
#'     A <- matrix(c(0, 1, -1, 1, 0, 0, -1, 0, 0), nrow = 3)
#'     centrality_scores <- betweenness_centrality(A)
#'     print(centrality_scores)
#' }
#' @export
betweenness_centrality_cpp <- function(A) {
    .Call('_SA24204144_betweenness_centrality_cpp', PACKAGE = 'SA24204144', A)
}

#' @title Compute Degree Centrality of Network
#' @description This function calculates the degree centrality of each node in a network 
#'              based on the adjacency matrix. The degree centrality is simply the number of 
#'              connections (edges) each node has in the network.
#' @param A A numeric matrix representing the adjacency matrix of the graph.
#'                   Each element is either 0 (no edge) or 1 (edge exists between nodes).
#' @return A numeric vector containing the degree centrality scores for each node. 
#'         The degree centrality for node `i` is the number of edges connected to node `i`.
#' @examples
#' \dontrun{
#'     A <- matrix(c(0, 1, 1, 0, 0,
#'                            1, 0, 1, 1, 0,
#'                            1, 1, 0, 1, 1,
#'                            0, 1, 1, 0, 1,
#'                            0, 0, 1, 1, 0), nrow = 5, byrow = TRUE)
#'     centrality_scores <- degree_centrality(A)
#'     print(centrality_scores)
#' }
#' @export
degree_centrality_cpp <- function(A) {
    .Call('_SA24204144_degree_centrality_cpp', PACKAGE = 'SA24204144', A)
}

